// <auto-generated />
using System;
using Coneic.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coneic.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903001533_AddVisitImagesAndBlockActive")]
    partial class AddVisitImagesAndBlockActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Coneic.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeakerId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Registro de asistentes y entrega de kits de bienvenida.",
                            EndTime = new DateTime(2026, 8, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hall Principal — UTN FRBA",
                            StartTime = new DateTime(2026, 8, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Acreditación y Bienvenida"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Conferencia magistral de apertura con visión integral sobre los desafíos actuales y futuros de la ingeniería civil argentina.",
                            EndTime = new DateTime(2026, 8, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Auditorio Principal",
                            SpeakerId = 1,
                            StartTime = new DateTime(2026, 8, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Charla Inaugural: La Ingeniería Civil del Futuro"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            EndTime = new DateTime(2026, 8, 4, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Patio del Campus",
                            StartTime = new DateTime(2026, 8, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Almuerzo"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Aplicación de BIM en proyectos de infraestructura vial y edilicia: flujos de trabajo, software y casos reales.",
                            EndTime = new DateTime(2026, 8, 4, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Laboratorio de Informática",
                            SpeakerId = 3,
                            StartTime = new DateTime(2026, 8, 4, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Taller: BIM aplicado a Infraestructura"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Criterios de diseño sísmico, normativa CIRSOC y análisis de estructuras ante solicitaciones dinámicas.",
                            EndTime = new DateTime(2026, 8, 4, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Sala de Estructuras",
                            SpeakerId = 1,
                            StartTime = new DateTime(2026, 8, 4, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Taller: Diseño Sismorresistente"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cena de inicio del congreso con networking y presentación de delegaciones de todo el país.",
                            EndTime = new DateTime(2026, 8, 4, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Salón de Eventos — Sede Central",
                            StartTime = new DateTime(2026, 8, 4, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cena de Bienvenida"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            EndTime = new DateTime(2026, 8, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hall Principal",
                            StartTime = new DateTime(2026, 8, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Acreditación"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Panorama actual de la infraestructura hídrica en Argentina: cuencas, embalses y gestión del agua en un contexto de cambio climático.",
                            EndTime = new DateTime(2026, 8, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Auditorio Principal",
                            SpeakerId = 2,
                            StartTime = new DateTime(2026, 8, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Charla Magistral: Infraestructura Hídrica"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Panel multidisciplinario sobre las obras más emblemáticas de Buenos Aires: subterráneos, autopistas, Puerto Madero y obras hidráulicas.",
                            EndTime = new DateTime(2026, 8, 5, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Auditorio Principal",
                            StartTime = new DateTime(2026, 8, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Panel: Obras Emblemáticas de Buenos Aires"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            EndTime = new DateTime(2026, 8, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Patio del Campus",
                            StartTime = new DateTime(2026, 8, 5, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Almuerzo"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Recorrido técnico guiado por las instalaciones y obras en curso del Puerto de Buenos Aires.",
                            EndTime = new DateTime(2026, 8, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Puerto Madero — Dique 4",
                            StartTime = new DateTime(2026, 8, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Visita Técnica: Puerto de Buenos Aires"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Noche de integración federal con música, gastronomía regional y actividades culturales.",
                            EndTime = new DateTime(2026, 8, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Salón de Eventos — Sede Central",
                            StartTime = new DateTime(2026, 8, 5, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Peña Federal"
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            EndTime = new DateTime(2026, 8, 6, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hall Principal",
                            StartTime = new DateTime(2026, 8, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Acreditación"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Exploración de hormigones especiales, geosintéticos y nanotecnología aplicados a la construcción moderna.",
                            EndTime = new DateTime(2026, 8, 6, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Laboratorio de Materiales",
                            SpeakerId = 4,
                            StartTime = new DateTime(2026, 8, 6, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Taller: Nuevos Materiales Constructivos"
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            EndTime = new DateTime(2026, 8, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Patio del Campus",
                            StartTime = new DateTime(2026, 8, 6, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Almuerzo"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Intervención constructiva voluntaria en una comunidad local de la zona sur de Buenos Aires.",
                            EndTime = new DateTime(2026, 8, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Comunidad La Paloma — Zona Sur",
                            StartTime = new DateTime(2026, 8, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Actividad Solidaria"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Reunión de representantes universitarios para tratar agenda de ANEIC, elección de sede 2027 y resoluciones.",
                            EndTime = new DateTime(2026, 8, 6, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Auditorio Principal",
                            StartTime = new DateTime(2026, 8, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Asamblea ANEIC"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Noche temática con folklore porteño, tango y gastronomía bonaerense.",
                            EndTime = new DateTime(2026, 8, 6, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Salón de Eventos — Sede Central",
                            StartTime = new DateTime(2026, 8, 6, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Noche Temática: Folklore Porteño"
                        },
                        new
                        {
                            Id = 19,
                            Description = "",
                            EndTime = new DateTime(2026, 8, 7, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hall Principal",
                            StartTime = new DateTime(2026, 8, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Acreditación"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Reflexión sobre sostenibilidad, cambio climático y el rol del ingeniero civil en la transición energética.",
                            EndTime = new DateTime(2026, 8, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Auditorio Principal",
                            SpeakerId = 2,
                            StartTime = new DateTime(2026, 8, 7, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Charla de Cierre: Sostenibilidad en la Ingeniería"
                        },
                        new
                        {
                            Id = 21,
                            Description = "",
                            EndTime = new DateTime(2026, 8, 7, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Patio del Campus",
                            StartTime = new DateTime(2026, 8, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Almuerzo"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Actividades recreativas, concursos y sorteos de premios especiales para los asistentes.",
                            EndTime = new DateTime(2026, 8, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Patio del Campus",
                            StartTime = new DateTime(2026, 8, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Actividad Recreativa y Sorteos"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Ceremonia oficial de cierre del XVIII CONEIC: entrega de diplomas, reconocimientos y palabras de despedida.",
                            EndTime = new DateTime(2026, 8, 7, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Auditorio Principal",
                            StartTime = new DateTime(2026, 8, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Acto de Clausura"
                        });
                });

            modelBuilder.Entity("Coneic.Api.Models.ActivityBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "VisitaTecnica",
                            IsActive = true,
                            MaxSelections = 1,
                            Name = "Visita Técnica",
                            Note = "Elegí una visita técnica. Cupos y horarios definitivos a confirmar."
                        },
                        new
                        {
                            Id = 2,
                            Category = "TallerCharla",
                            IsActive = false,
                            MaxSelections = 1,
                            Name = "Talleres y Charlas Simultáneas",
                            Note = "Agrupación provisoria de demo — los bloques horarios reales todavía se están definiendo con Académica y GyP."
                        });
                });

            modelBuilder.Entity("Coneic.Api.Models.ActivitySelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail", "BlockId")
                        .IsUnique();

                    b.ToTable("ActivitySelections");
                });

            modelBuilder.Entity("Coneic.Api.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Coneic.Api.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckedInBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId", "SessionId")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("Coneic.Api.Models.AttendanceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AttendanceSessions");
                });

            modelBuilder.Entity("Coneic.Api.Models.ManualComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ManualComments");
                });

            modelBuilder.Entity("Coneic.Api.Models.PaymentBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assignments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DelegateEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DelegationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeedsInvoice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaymentBatches");
                });

            modelBuilder.Entity("Coneic.Api.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Coneic.Api.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPending")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttendanceConfidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DietaryRestrictions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InterestedInMaccaferri")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalConditions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ParticipatedInJoreic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReceiptUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("University")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Coneic.Api.Models.SelectableActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speaker")
                        .HasColumnType("TEXT");

                    b.Property<int>("TakenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SelectableActivities");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.01",
                            Description = "El objetivo del taller es acompañar a estudiantes de la carrera con la duda de qué sucede una vez recibido, cómo posicionarse en el mercado laboral y qué posibilidades hay hoy en día para ingenieros civiles.",
                            Speaker = "Ing. Axel Colantuono, CRIBA",
                            TakenCount = 0,
                            Title = "¿Y ahora qué?"
                        },
                        new
                        {
                            Id = 102,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.02",
                            Description = "Introducción accesible a la IA conversacional, con foco en Claude: qué es un modelo de lenguaje, por qué puede alucinar y cómo usarla de forma más eficiente y responsable en la formación y el ejercicio profesional.",
                            Speaker = "Dr. Felipe Ruiz Bruzzone",
                            TakenCount = 0,
                            Title = "Más allá del chat: fundamentos y aplicaciones prácticas de la IA"
                        },
                        new
                        {
                            Id = 103,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.03",
                            Description = "Identificar causas probables de derrumbes. Prevenciones.",
                            Speaker = "Ing. Claudio Silvio Risetto",
                            TakenCount = 0,
                            Title = "Derrumbes. Casos."
                        },
                        new
                        {
                            Id = 104,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.04",
                            Description = "Presentación de casos reales de diagnóstico estructural mediante tecnologías avanzadas. Cómo identificar patologías, comprender el comportamiento del hormigón y definir estrategias técnicas de intervención eficiente.",
                            Speaker = "Ing. Julio Cesar Tomás, ITAC Laboratorio",
                            TakenCount = 0,
                            Title = "Cómo la tecnología está cambiando la forma de diagnosticar estructuras de hormigón"
                        },
                        new
                        {
                            Id = 105,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.05",
                            Description = "Cómo realizar la ingeniería de detalle en instalaciones MEP para obtener modelos digitales listos para fabricación. Detección temprana de interferencias y tolerancias de montaje para asegurar que estructura e instalaciones convivan en armonía.",
                            Speaker = "Ing. María Anahí Zoratto Macia",
                            TakenCount = 0,
                            Title = "Ingeniería de detalle y coordinación de instalaciones: diseñar en la computadora para construir sin errores en la obra"
                        },
                        new
                        {
                            Id = 106,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.06",
                            Description = "Introducción al flujo de trabajo del ingeniero MEP dentro del entorno BIM. Transición de esquemas tradicionales 2D a modelos 3D interactivos para coordinar conductos, tuberías y cables antes de ir a obra, evitando errores millonarios.",
                            Speaker = "Ing. María Anahí Zoratto Macia",
                            TakenCount = 0,
                            Title = "Del plano 2D al modelo 3D: cómo la ingeniería MEP digital transforma el diseño de instalaciones"
                        },
                        new
                        {
                            Id = 107,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.07",
                            Description = "Criterio técnico en hormigón armado: análisis de cómo la simplificación del Bloque Equivalente de Whitney rige las ecuaciones clave de ACI 318 y CIRSOC 201.",
                            Speaker = "Ing. Bryan Alejandro Castañón, ANEIC Guatemala",
                            TakenCount = 0,
                            Title = "De la distribución real de tensiones al modelo simplificado: impacto en la práctica del Ingeniero Civil"
                        },
                        new
                        {
                            Id = 108,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.08",
                            Description = "Simulación operativa en software de presas hidroeléctricas con juego de roles para la toma de decisiones en generación energética, control de crecidas y gestión ambiental.",
                            Speaker = "Ing. Gerardo Burdisso",
                            TakenCount = 0,
                            Title = "Sistema de complejos Hidroeléctricos COMAHUE - Río Limay: taller de práctica de roles en sectores de interés público, privado y sociedad"
                        },
                        new
                        {
                            Id = 109,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.09",
                            Description = "Práctica en equipo sobre un caso simulado de obra civil en tiempo real: identificación de impactos ambientales, aplicación de jerarquías de mitigación y resolución de imprevistos en obra.",
                            Speaker = "Lic. Romina Favilla",
                            TakenCount = 0,
                            Title = "La obra que no contamina: taller de gestión ambiental para ingenieros civiles"
                        },
                        new
                        {
                            Id = 110,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "1.10",
                            Description = "Un edificio, un puente, una presa: obras distintas que se sostienen —o se caen— por lo mismo. En este taller no vas a escuchar la teoría, la vas a construir con tus manos y en equipo. Diseñá tu estructura sobre un terreno real, cargala hasta el límite y descubrí en vivo cómo el agua cambia las reglas del juego.",
                            Speaker = "Ing. Gustavo Daniel Mosquera",
                            TakenCount = 0,
                            Title = "¿Aguanta o no Aguanta? Taller de Geotecnia en Acción"
                        },
                        new
                        {
                            Id = 201,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "2.01",
                            Description = "Tecnología aplicada, fundamentos y entorno de la metodología BIM, y su integración con la gestión eficiente en obra.",
                            Speaker = "Ing. Martín Magallanes",
                            TakenCount = 0,
                            Title = "El ecosistema BIM en la Ingeniería Civil: de los fundamentos teóricos a la tecnología aplicada"
                        },
                        new
                        {
                            Id = 202,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "2.02",
                            Description = "Integración del conocimiento técnico y el derecho a la vida silvestre en la infraestructura: impacto de los atropellamientos de fauna y soluciones de ingeniería aplicada.",
                            Speaker = "Lic. Nicolás Lodeiro Ocampo",
                            TakenCount = 0,
                            Title = "Rutas y Fauna Silvestre, es tiempo de pensar a todas las vidas"
                        },
                        new
                        {
                            Id = 203,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "2.03",
                            Description = "Por qué el criterio y la conciencia son el verdadero valor diferencial frente a la automatización técnica, y herramientas para liderar tu propio desarrollo en la próxima década.",
                            Speaker = "Ing. Joaquín N. Perrig",
                            TakenCount = 0,
                            Title = "Aprender a ApreHender: el diferencial humano frente al avance tecnológico"
                        },
                        new
                        {
                            Id = 204,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "2.04",
                            Description = "Desafíos técnicos y operativos superados en proyectos reales, implementación de la tecnología a escala nacional y lecciones aprendidas.",
                            Speaker = "Ing. Rocío Gentico, Techint",
                            TakenCount = 0,
                            Title = "Impresión 3D de hormigón en Argentina: desafíos y aprendizajes en proyectos reales"
                        },
                        new
                        {
                            Id = 205,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "2.05",
                            Description = "Gestión sustentable, técnicas avanzadas de demolición según escala de obra y economía circular con residuos de construcción y demolición (RCD).",
                            Speaker = "Ing. Maximiliano Mauriño, Grupo Mitre",
                            TakenCount = 0,
                            Title = "Demolición, Excavación y Reciclaje en Obras de Gran Escala"
                        },
                        new
                        {
                            Id = 206,
                            BlockId = 2,
                            Capacity = 40,
                            Code = "2.06",
                            Description = "Catalogación de fallas, evolución constructiva e ingeniería forense: análisis exhaustivo de daños estructurales, geomorfológicos y socioeconómicos tras el evento sísmico.",
                            Speaker = "Ing. Gustavo Delgado",
                            TakenCount = 0,
                            Title = "Terremoto 2026 en Venezuela: ingeniería forense y lecciones aprendidas"
                        },
                        new
                        {
                            Id = 401,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.01",
                            Description = "Pionera de la Energía Nuclear en América Latina.",
                            ImageUrl = "/assets/visitas/visita-4-01.jpg",
                            TakenCount = 0,
                            Title = "Complejo Nuclear Atucha"
                        },
                        new
                        {
                            Id = 402,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.02",
                            Description = "Ingeniería portuaria y logística multimodal a gran escala.",
                            ImageUrl = "/assets/visitas/visita-4-02.jpg",
                            TakenCount = 0,
                            Title = "Puerto Buenos Aires"
                        },
                        new
                        {
                            Id = 403,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.03",
                            Description = "Ingeniería ambiental y gestión de residuos a escala metropolitana.",
                            ImageUrl = "/assets/visitas/visita-4-03.jpg",
                            TakenCount = 0,
                            Title = "Complejo Ambiental Norte III"
                        },
                        new
                        {
                            Id = 404,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.04",
                            Description = "1.950.000 m³/día de agua tratada para la región metropolitana.",
                            ImageUrl = "/assets/visitas/visita-4-04.jpg",
                            TakenCount = 0,
                            Title = "Planta Potabilizadora Gral. Belgrano"
                        },
                        new
                        {
                            Id = 405,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.05",
                            Description = "237.000 m³/día de líquidos tratados. Sirve a gran parte del partido de La Matanza.",
                            ImageUrl = "/assets/visitas/visita-4-05.jpg",
                            TakenCount = 0,
                            Title = "Planta Depuradora Sudoeste"
                        },
                        new
                        {
                            Id = 406,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.06",
                            Description = "23.328 m³/día de efluentes tratados. Saneamiento directo para 90.000 habitantes.",
                            ImageUrl = "/assets/visitas/visita-4-06.jpg",
                            TakenCount = 0,
                            Title = "Planta Depuradora Lanús"
                        },
                        new
                        {
                            Id = 407,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.07",
                            Description = "48.000 m³/día de efluentes tratados. Operativa para Ezeiza y parte de Esteban Echeverría.",
                            ImageUrl = "/assets/visitas/visita-4-07.jpg",
                            TakenCount = 0,
                            Title = "Planta Depuradora El Jagüel"
                        },
                        new
                        {
                            Id = 408,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.08",
                            Description = "77.760 m³/día de efluentes tratados. Beneficia a 270.000 habitantes.",
                            ImageUrl = "/assets/visitas/visita-4-08.jpg",
                            TakenCount = 0,
                            Title = "Planta Depuradora Fiorito"
                        },
                        new
                        {
                            Id = 409,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.09",
                            Description = "Elementos de hormigón premoldeado. Tecnología y estandarización a gran escala para la industria de la construcción.",
                            ImageUrl = "/assets/visitas/visita-4-09.jpg",
                            TakenCount = 0,
                            Title = "Planta de Hormigón Sola"
                        },
                        new
                        {
                            Id = 410,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.10",
                            Description = "30.240 m³/día de efluentes tratados. Sirve a Hurlingham, Ituzaingó, Morón y Tres de Febrero.",
                            ImageUrl = "/assets/visitas/visita-4-10.jpg",
                            TakenCount = 0,
                            Title = "Planta Depuradora Hurlingham"
                        },
                        new
                        {
                            Id = 411,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.11",
                            Description = "Producción y logística de hormigón elaborado. El detrás de la dosificación y distribución para obras de gran porte.",
                            ImageUrl = "/assets/visitas/visita-4-11.jpg",
                            TakenCount = 0,
                            Title = "Fenomix"
                        },
                        new
                        {
                            Id = 412,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.12",
                            Description = "Infraestructura costera y portuaria. Soluciones de ingeniería para el almacenamiento y movimiento de embarcaciones.",
                            ImageUrl = "/assets/visitas/visita-4-12.jpg",
                            TakenCount = 0,
                            Title = "Guardería Náutica Neptuno"
                        },
                        new
                        {
                            Id = 413,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.13",
                            Description = "Un proyecto de GNV Group para transformar la vida urbana en Puerto Madero.",
                            ImageUrl = "/assets/visitas/visita-4-13.jpg",
                            TakenCount = 0,
                            Title = "Madero Harbour"
                        },
                        new
                        {
                            Id = 414,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.14",
                            Description = "Primera en su tipo adquirida por una empresa constructora en Argentina.",
                            ImageUrl = "/assets/visitas/visita-4-14.jpg",
                            TakenCount = 0,
                            Title = "Impresora 3D de Concreto"
                        },
                        new
                        {
                            Id = 415,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.15",
                            Description = "Una obra de usos mixtos que integra residencias de lujo, un hotel cinco estrellas y 7.600 m² de amenidades de primer nivel.",
                            ImageUrl = "/assets/visitas/visita-4-15.jpg",
                            TakenCount = 0,
                            Title = "Proyecto Udaondo"
                        },
                        new
                        {
                            Id = 416,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.16",
                            Description = "Un proyecto inmobiliario en una de las zonas con mayor proyección de Buenos Aires, que integra el diseño urbano y entorno natural.",
                            ImageUrl = "/assets/visitas/visita-4-16.jpg",
                            TakenCount = 0,
                            Title = "Quartier Bajo Belgrano"
                        },
                        new
                        {
                            Id = 417,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.17",
                            Description = "Será la primera autopista parque de la Ciudad, diseñada para optimizar la movilidad y el espacio público.",
                            ImageUrl = "/assets/visitas/visita-4-17.jpg",
                            TakenCount = 0,
                            Title = "Autopista Parque Dellepiane"
                        },
                        new
                        {
                            Id = 418,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.18",
                            Description = "Complejo residencial que combina departamentos con grandes espacios verdes y servicios premium propios de un barrio cerrado dentro de la ciudad.",
                            ImageUrl = "/assets/visitas/visita-4-18.jpg",
                            TakenCount = 0,
                            Title = "MilAires"
                        },
                        new
                        {
                            Id = 419,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.19",
                            Description = "Ampliación y renovación del puente que conecta el Parque de la Innovación y la Ciudad Universitaria.",
                            ImageUrl = "/assets/visitas/visita-4-19.jpg",
                            TakenCount = 0,
                            Title = "Puente Labruna"
                        },
                        new
                        {
                            Id = 420,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.20",
                            Description = "Nueva conexión entre la Ciudad y el Río de la Plata que mejorará la movilidad e integrará el entorno.",
                            ImageUrl = "/assets/visitas/visita-4-20.jpg",
                            TakenCount = 0,
                            Title = "Anillo Pampa"
                        },
                        new
                        {
                            Id = 421,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.21",
                            Description = "Nueva torre de 17 pisos y 4 subsuelos en Belgrano: departamentos de hasta 555 m² con pileta propia, spa, gimnasio y pileta en la terraza.",
                            ImageUrl = "/assets/visitas/visita-4-21.jpg",
                            TakenCount = 0,
                            Title = "Ñlet Loreto"
                        },
                        new
                        {
                            Id = 422,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.22",
                            Description = "Megaobra histórica del Más Monumental: techado integral, tribuna 360° y ampliación de capacidad a 101.000 espectadores con cerca de 100 columnas perimetrales.",
                            ImageUrl = "/assets/visitas/visita-4-22.jpg",
                            TakenCount = 0,
                            Title = "Estadio Más Monumental"
                        },
                        new
                        {
                            Id = 423,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.23",
                            Description = "Modernización integral y preservación patrimonial: un complejo emblemático de 42.000 m² compuesto por una torre de 12 pisos, cuerpo bajo y 6 subsuelos.",
                            ImageUrl = "/assets/visitas/visita-4-23.jpg",
                            TakenCount = 0,
                            Title = "Centro Cultural San Martín"
                        },
                        new
                        {
                            Id = 424,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.24",
                            Description = "Nueva infraestructura educativa de 2.900 m² en el Barrio 31: diseño bioclimático, sistemas constructivos industrializados y espacios de alta funcionalidad pedagógica.",
                            ImageUrl = "/assets/visitas/visita-4-24.jpg",
                            TakenCount = 0,
                            Title = "Escuela Indira Gandhi"
                        },
                        new
                        {
                            Id = 425,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.25",
                            Description = "Obra residencial de 13.677 m² (2, 3 y 4 ambientes). Trabajos actuales: estructura en 5° piso, inicio de albañilería y grúa torre con trepado.",
                            ImageUrl = "/assets/visitas/visita-4-25.jpg",
                            TakenCount = 0,
                            Title = "Complejo Dorrego Plaza"
                        },
                        new
                        {
                            Id = 426,
                            BlockId = 1,
                            Capacity = 30,
                            Code = "4.26",
                            Description = "70.000 m² cubiertos. Desarrollo de usos mixtos (hotel de lujo, viviendas, oficinas y plaza pública) con un 35% de factor de ocupación y 65% de espacio público.",
                            ImageUrl = "/assets/visitas/visita-4-26.jpg",
                            TakenCount = 0,
                            Title = "JN4016"
                        });
                });

            modelBuilder.Entity("Coneic.Api.Models.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Especialista en diseño sísmico y estructuras de gran escala con más de 20 años de trayectoria en obras de infraestructura.",
                            ImageUrl = "https://randomuser.me/api/portraits/men/32.jpg",
                            LinkedInUrl = "#",
                            Name = "Ing. Roberto Fernández",
                            Title = "Especialista en Estructuras y Sismología"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Investigadora en hidráulica e ingeniería ambiental. Autora de numerosas publicaciones sobre gestión de recursos hídricos en la cuenca del Plata.",
                            ImageUrl = "https://randomuser.me/api/portraits/women/44.jpg",
                            LinkedInUrl = "#",
                            Name = "Dra. Laura Gómez",
                            Title = "Ingeniería Hidráulica y Ambiental"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Referente nacional en implementación de BIM en proyectos de infraestructura vial y edilicia. Docente en UTN y UBA.",
                            ImageUrl = "https://randomuser.me/api/portraits/men/55.jpg",
                            LinkedInUrl = "#",
                            Name = "Ing. Diego Torres",
                            Title = "BIM y Tecnología en la Construcción"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Investigadora del CONICET en nuevos materiales constructivos: hormigones especiales, geosintéticos y nanotecnología aplicada.",
                            ImageUrl = "https://randomuser.me/api/portraits/women/61.jpg",
                            LinkedInUrl = "#",
                            Name = "Ing. Valeria Ríos",
                            Title = "Nuevos Materiales y Nanotecnología"
                        });
                });

            modelBuilder.Entity("Coneic.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DelegationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filial")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagedFaculties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quota")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Coneic.Api.Models.Activity", b =>
                {
                    b.HasOne("Coneic.Api.Models.Speaker", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId");

                    b.Navigation("Speaker");
                });
#pragma warning restore 612, 618
        }
    }
}
