// <auto-generated />
using System;
using Coneic.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coneic.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116204418_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Coneic.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpeakerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeakerId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bienvenida al XVII CONEIC",
                            EndTime = new DateTime(2026, 10, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Auditorio Principal",
                            StartTime = new DateTime(2026, 10, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Apertura"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Diseño moderno de puentes.",
                            EndTime = new DateTime(2026, 10, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Auditorio Principal",
                            SpeakerId = 1,
                            StartTime = new DateTime(2026, 10, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Charla Magistral: Puentes"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Introducción a Building Information Modeling.",
                            EndTime = new DateTime(2026, 10, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Sala A",
                            SpeakerId = 2,
                            StartTime = new DateTime(2026, 10, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Taller: BIM"
                        });
                });

            modelBuilder.Entity("Coneic.Api.Models.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Experto en diseño sismorresistente.",
                            ImageUrl = "https://via.placeholder.com/150",
                            LinkedInUrl = "#",
                            Name = "Ing. Juan Pérez",
                            Title = "Especialista en Estructuras"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Investigadora en recursos hídricos.",
                            ImageUrl = "https://via.placeholder.com/150",
                            LinkedInUrl = "#",
                            Name = "Dra. María González",
                            Title = "Ingeniería Ambiental"
                        });
                });

            modelBuilder.Entity("Coneic.Api.Models.Activity", b =>
                {
                    b.HasOne("Coneic.Api.Models.Speaker", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId");

                    b.Navigation("Speaker");
                });
#pragma warning restore 612, 618
        }
    }
}
